<a href="https://colab.research.google.com/github/Elma-dev/NLP_basics/blob/main/NLP_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
corpus=np.array([
    "Dog bites man",
    "Man bites dog",
    "Dog eats meat.",
    "Man eats food"
])

# **Bag Of Words**

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
count_vect=CountVectorizer()

In [5]:
bow_rep=count_vect.fit_transform(corpus)

In [6]:
print(f"our vocabulary:{count_vect.vocabulary_}")

our vocabulary:{'dog': 1, 'bites': 0, 'man': 4, 'eats': 2, 'meat': 5, 'food': 3}


In [7]:
print(f"bow({corpus[0]})={bow_rep[0].toarray()}")
print(f"bow({corpus[1]})={bow_rep[1].toarray()}")

bow(Dog bites man)=[[1 1 0 0 1 0]]
bow(Man bites dog)=[[1 1 0 0 1 0]]


In [8]:
count_vect.transform(["Man and Man are friends"]).toarray()

array([[0, 0, 0, 0, 2, 0]])

# **Bag Of N-Grams**

In [9]:
ngram_vect=CountVectorizer(ngram_range=(1,3))

In [10]:
bon_rep=ngram_vect.fit_transform(corpus)

In [11]:
print(f"vocabulary: {ngram_vect.vocabulary_}")

vocabulary: {'dog': 3, 'bites': 0, 'man': 12, 'dog bites': 4, 'bites man': 2, 'dog bites man': 5, 'man bites': 13, 'bites dog': 1, 'man bites dog': 14, 'eats': 8, 'meat': 17, 'dog eats': 6, 'eats meat': 10, 'dog eats meat': 7, 'food': 11, 'man eats': 15, 'eats food': 9, 'man eats food': 16}


In [12]:
print(f"bon({corpus[0]})= {bon_rep.toarray()[0]}")
print(f"bon({corpus[1]})= {bon_rep.toarray()[1]}")

bon(Dog bites man)= [1 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0]
bon(Man bites dog)= [1 1 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0]


In [13]:
ngram_vect.transform(["Man and Man are friends"]).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0]])

# **TF-IDF**

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
tfIdfVect=TfidfVectorizer(use_idf=True)

In [16]:
tfIdf_rep=tfIdfVect.fit_transform(corpus)

In [17]:
tfIdfVect.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.91629073, 1.22314355,
       1.91629073])

In [18]:
tfIdfVect.get_feature_names_out()

array(['bites', 'dog', 'eats', 'food', 'man', 'meat'], dtype=object)

In [19]:
tfIdf_rep.toarray()

array([[0.65782931, 0.53256952, 0.        , 0.        , 0.53256952,
        0.        ],
       [0.65782931, 0.53256952, 0.        , 0.        , 0.53256952,
        0.        ],
       [0.        , 0.44809973, 0.55349232, 0.        , 0.        ,
        0.70203482],
       [0.        , 0.        , 0.55349232, 0.70203482, 0.44809973,
        0.        ]])

# **Word2Vec**

In [23]:
from gensim.models import Word2Vec,KeyedVectors
import gensim.downloader

In [26]:
gensim.downloader.info()["models"].keys()

dict_keys(['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis'])

In [27]:
glove_twit_=gensim.downloader.load("glove-twitter-100")

[==================================================] 100.0% 387.1/387.1MB downloaded


In [32]:
print("the most simailar words of 'beautiful'\n",glove_twit.most_similar("beautiful"))

the most simailar words of 'beautiful'
 [('gorgeous', 0.8894475698471069), ('lovely', 0.8454167246818542), ('amazing', 0.8415848016738892), ('wonderful', 0.8386240601539612), ('pretty', 0.8151682615280151), ('perfect', 0.8063325881958008), ('stunning', 0.7912963628768921), ('love', 0.7891266942024231), ('fabulous', 0.7720125913619995), ('great', 0.7551646828651428)]


In [33]:
#representation vector of "beautiful"
glove_twit["beautiful"]

array([-2.4458e-01, -1.5625e-01, -1.0662e-01,  1.0301e+00,  4.5470e-01,
       -5.4162e-02,  6.6871e-01, -1.1156e-01, -2.5903e-01, -4.8663e-01,
       -6.3634e-01,  4.9448e-02, -3.9373e+00, -7.4904e-01, -1.5832e-01,
        2.8391e-01,  4.6099e-01, -8.8693e-01, -2.7598e-01, -4.5481e-02,
        4.7407e-01, -5.4822e-01, -2.0248e-01, -2.1185e-01,  4.4775e-01,
        4.0185e-02, -3.2798e-01,  2.2575e-01,  1.2254e-03, -5.3821e-02,
       -5.1709e-01, -3.7126e-01, -9.7558e-02,  2.1935e-01,  2.7947e-02,
        1.1592e-01,  1.4783e-01, -4.4554e-01, -6.8792e-01, -8.7646e-02,
       -7.1567e-01, -5.6389e-01,  1.8504e-01,  6.9230e-01,  1.9744e-01,
        3.4417e-01,  1.2001e+00, -8.3236e-01, -4.9701e-01, -4.1647e-01,
       -6.1386e-01, -1.8944e-01,  1.9585e-01, -1.2800e+00,  8.8118e-01,
        3.1454e-01, -3.6886e-01, -2.9003e-01,  3.5148e-01, -7.8839e-02,
        2.0294e-01, -2.0052e-02, -6.4219e-01, -5.1995e-01,  7.3575e-02,
        3.4568e-01, -1.0480e+00, -3.6306e-01, -4.3392e-01,  4.85