<a href="https://colab.research.google.com/github/Elma-dev/NLP_basics/blob/main/NLP_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
corpus=np.array([
    "Dog bites man",
    "Man bites dog",
    "Dog eats meat.",
    "Man eats food"
])

# **Bag Of Words**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
count_vect=CountVectorizer()

In [ ]:
bow_rep=count_vect.fit_transform(corpus)

In [ ]:
print(f"our vocabulary:{count_vect.vocabulary_}")

our vocabulary:{'dog': 1, 'bites': 0, 'man': 4, 'eats': 2, 'food': 3}


In [ ]:
print(f"bow({corpus[0]})={bow_rep[0].toarray()}")
print(f"bow({corpus[1]})={bow_rep[1].toarray()}")

bow(Dog bites man)=[[1 1 0 0 1]]
bow(Man bites dog)=[[1 1 0 0 1]]


In [ ]:
count_vect.transform(["Man and Man are friends"]).toarray()

array([[0, 0, 0, 0, 2]])

# **Bag Of N-Grams**

In [ ]:
ngram_vect=CountVectorizer(ngram_range=(1,3))

In [ ]:
bon_rep=ngram_vect.fit_transform(corpus)

In [ ]:
print(f"vocabulary: {ngram_vect.vocabulary_}")

vocabulary: {'dog': 3, 'bites': 0, 'man': 9, 'dog bites': 4, 'bites man': 2, 'dog bites man': 5, 'man bites': 10, 'bites dog': 1, 'man bites dog': 11, 'eats': 6, 'food': 8, 'man eats': 12, 'eats food': 7, 'man eats food': 13}


In [ ]:
print(f"bon({corpus[0]})= {bon_rep.toarray()[0]}")
print(f"bon({corpus[1]})= {bon_rep.toarray()[1]}")

bon(Dog bites man)= [1 0 1 1 1 1 0 0 0 1 0 0 0 0]
bon(Man bites dog)= [1 1 0 1 0 0 0 0 0 1 1 1 0 0]


In [ ]:
ngram_vect.transform(["Man and Man are friends"]).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0]])

# **TF-IDF**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfIdfVect=TfidfVectorizer(use_idf=True)

In [ ]:
tfIdf_rep=tfIdfVect.fit_transform(corpus)

In [ ]:
tfIdfVect.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.91629073, 1.22314355,
       1.91629073])

In [ ]:
tfIdfVect.get_feature_names_out()

array(['bites', 'dog', 'eats', 'food', 'man', 'meat'], dtype=object)

In [ ]:
tfIdf_rep.toarray()

array([[0.65782931, 0.53256952, 0.        , 0.        , 0.53256952,
        0.        ],
       [0.65782931, 0.53256952, 0.        , 0.        , 0.53256952,
        0.        ],
       [0.        , 0.44809973, 0.55349232, 0.        , 0.        ,
        0.70203482],
       [0.        , 0.        , 0.55349232, 0.70203482, 0.44809973,
        0.        ]])